info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/CreateUser:
    get:
      description: 新增用户接口
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 第二次输入的密码
        in: query
        name: repassword
        required: true
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
        "400":
          description: code","message"}
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/DeleteUser:
    get:
      description: 删除用户接口
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /user/GetUserList:
    get:
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 所有用户
      tags:
      - 用户模块
  /user/UpdateUser:
    post:
      description: 更新用户接口
      parameters:
      - description: id
        in: formData
        name: id
        type: string
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: string
      - description: email
        in: formData
        name: email
        type: string
      - description: phone
        in: formData
        name: phone
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 更新用户
      tags:
      - 用户模块
  /user/UserLogin:
    post:
      description: 用户登录接口
      parameters:
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户模块
swagger: "2.0"
